[build]
    publish = "dist"
    command = "yarn build"
[[redirects]]
  from = "/complex-variables/*"
  to = "https://complexvariables.netlify.app:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}