name: update
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download template repo
        uses: actions/checkout@v2
        with:
          repository: dylan-wu/template-11ty-vredeburg
          path: template
          token: ${{ secrets.REPO_CHECKOUT }}
      - name: Install latest coda data
        run: |
          rm -rf template/.git
          ls -la template
          ls -la template/src/
      - name: Running script
        run: |
          src/update.sh
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
